name: build-package
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Target package'
        type: string
        default: 'test_pubsub'
        required: true
      debug-mode:
        description: 'Debug mode'
        type: boolean
        default: false
run-name: Build up to package ${{ inputs.package }}


jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      TARGET_PLATFORM: emscripten-32
      RMW_IMPLEMENTATION: rmw_wasm
      ROS_VERSION: 2
      ROS_DISTRO: humble

    steps:

    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: 3.1.27
      
    - name: Verify emsdk
      run: |
        emcc -v
        find $EMSDK -iname "upstream"
        echo "Find upstream"

    - name: Create ROS2 workspace
      run: mkdir -p ros_workspace/src

    - name: Install rmw_wasm
      uses: actions/checkout@v3
      with:
        path: ros_workspace/src/myrepo

    - name: Copy ROS2 packages
      run:  |
        curl -s https://packagecloud.io/install/repositories/dirk-thomas/vcstool/script.deb.sh | sudo bash
        sudo apt-get update
        sudo apt-get install python3-vcstool
        vcs import --input https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos ros_workspace/src
        vcs import --input ros_workspace/src/myrepo/src/repos.yaml ros_workspace/src

    - name: Remove unsupported packages
      run: |
        cd ros_workspace/src
        while read F; do rm -rf $F; done < myrepo/src/unsupported.txt

    - name: Apply patches
      run: |
        cd ros_workspace/src/ros2/rcutils
        git apply ${GITHUB_WORKSPACE}/ros_workspace/src/myrepo/src/rcutils.patch

    - name: Create environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: ros_workspace/src/myrepo/src/env.yaml
        environment-name: ros-env
        micromamba-version: '1.4.1'
    
    - name: Activate environment and build package
      run: |
        eval "$(micromamba shell hook --shell=bash)"
        micromamba activate ros-env
        cd ros_workspace
        if [${{ inputs.debug }}]; then ./src/myrepo/src/blasm.sh -d -v -u ${{ inputs.package }}; else ./src/myrepo/src/blasm.sh -u ${{ inputs.package }}; fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.package }}-artifacts
        path: |
          ros_workspace/build/${{ inputs.package }}/*.js
          ros_workspace/build/${{ inputs.package }}/*.wasm
          ros_workspace/build/${{ inputs.package }}/*.html
      